### ISSUE TITLE
duplicate of gulp-replace

### ISSUE THREAD

**Issue by sindresorhus** [mikrofusion/gulp-regex-replace#1]
https://github.com/lazd/gulp-replace

// @lazd

**Comment by mikrofusion** [comment]
Hi @sindresorhus!  Although gulp-replace also allows replacement of test matching regular expressions, there are actually features in gulp-regex-replace (some implemented and some to be implemented shortly) that are currently not in gulp-replace.  The first critical feature is the ability to have the replace string be a function... others will be the ability to return a subset of the string matched.  

This project was actually originally part of gulp-obfuscate (https://www.npmjs.org/package/gulp-obfuscate) but I was felt there was enough useful code to warrant this being a stand alone project.  The features I am implementing here are basically pre-requisites to the features I plan on implementing for gulp-obfuscate.

Thanks for your input - I am a fan of a lot of your work on github.
- mike

**Comment by lazd** [comment]
Hey Mike, FYI gulp-replace has supported using a function as the replacement value since the first release.

I'd rather avoid fragmentation and parallel efforts, and I would be open to a PR to get gulp-replace caught up with gulp-regex-replace for the features that are missing. However, if you feel it makes sense to keep the plugins separate because the features in your version are too complicated for the usual use cases, I'm fine with that as well.
